version: "3"
services:
  flask:
    build:
      context: backend
      dockerfile: Dockerfile
    hostname: backend-flask
    container_name: backend-flask
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - appdata:/var/www
    depends_on:
      - db

  db:
    build:
      context: mongodb
      dockerfile: Dockerfile
    container_name: db-mongo
    environment:
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=adminpass
      - MONGODB_APPLICATION_DATABASE=mytestdatabase
      - MONGODB_APPLICATION_USER=testuser
      - MONGODB_APPLICATION_PASS=testpass
    ports:
      - "27018:27017"
    volumes:
      - mongodbdata:/data/db

  react:
    build:
      context: frontend
      dockerfile: Dockerfile
    hostname: frontend-react
    container_name: frontend-react
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - reactdata:/var/log/react
    depends_on:
      - flask

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
  reactdata:
    driver: local
