version: "3"

services:
  flask:
    build:
      context: backend
      dockerfile: Dockerfile
    hostname: backend-flask
    container_name: backend-flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      frontend:
        ipv4_address: 10.5.0.5
      backend:
        ipv4_address: 10.6.0.5

  db:
    build:
      context: mongodb
      dockerfile: Dockerfile
    container_name: db-mongo
    hostname: mongo
    environment:
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=adminpass
      - MONGODB_APPLICATION_DATABASE=mytestdatabase
      - MONGODB_APPLICATION_USER=testuser
      - MONGODB_APPLICATION_PASS=testpass
    restart: always
    ports:
      - "27017:27017"
    expose:
      - 27017
    networks:
      backend:
        ipv4_address: 10.6.0.6

  react:
    build:
      context: frontend
      dockerfile: Dockerfile
    hostname: frontend-react
    container_name: frontend-react
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - flask
    networks:
      frontend:
        ipv4_address: 10.5.0.6

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
