swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Interpolation Tool ReST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /cords:
    get:
      operationId: api.cords.read_all
      tags:
        - All-elements of points
      summary: Read the entire list of elements
      description: Read the entire list of elements
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of elements to get
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering points
          required: false
      responses:
        200:
          description: Successfully read points list operation
          schema:
            type: array
            items:
              properties:
                id_element:
                  type: integer
                  description: id of element
                x_values:
                  type: "array"
                  items:
                    type: "number"
                    description: x cordinates of points to interpolation
                y_values:
                  type: array
                  items:
                    type: "number"
                    description: y cordinates of points to interpolation
                interp_x:
                  type: "array"
                  items:
                    type: "number"
                    description: x cordinates of points after interpolation
                interp_y:
                  type: array
                  items:
                    type: "number"
                    description: y cordinates of points after interpolation
                method:
                  type: string
                  description: interpolation method of points

    post:
      operationId: api.cords.create
      tags:
        - All-elements of points
      summary: Create a element and add it to list
      description: Create a element and add it to list
      parameters:
        - name: element
          in: body
          description: Element to create
          required: True
          schema:
            type: object
            properties:
              id_element:
                type: integer
                description: id of element to create
              x_val:
                type: "array"
                items:
                  type: "number"
                description: x cordinate of elements to interpolation to create
              y_val:
                type: array
                items:
                  type: "number"
                description: y cordinate of elements to interpolation to create
              method:
                type: string
                description: interpolation method of element to create
      responses:
        201:
          description: Successfully created element in list to interpolation

  /cords/{id_element}:
    get:
      operationId: api.cords.read_one
      tags:
        - 1-element of points
      summary: Read one element from list
      description: Read one element from list
      parameters:
        - name: id_element
          in: path
          description: Id of the element to get from the list
          type: integer
          required: True
      responses:
        200:
          description: Successfully read element from list
          schema:
            properties:
              x_val:
                type: "array"
                items:
                  type: "number"
                description: x cordinate of elements to interolation
              y_val:
                type: array
                items:
                  type: "number"
                description: y cordinate of elements to interolation
              method:
                type: string
                description: interpolation method of elements

    put:
      operationId: api.cords.update
      tags:
        - 1-element of points
      summary: Update a element in the list
      description: Update a element in the list
      parameters:
        - name: id_element
          in: path
          description: Id of the element to update from the list
          type: integer
          required: True
        - name: element
          in: body
          schema:
            type: object
            properties:
              x_val:
                type: "array"
                items:
                  type: "number"
                description: x cordinate of elements to interolation to update
              y_val:
                type: array
                items:
                  type: "number"
                description: y cordinate of elements to interolation to update
              method:
                type: string
                description: interpolation method of elementto update
      responses:
        200:
          description: Successfully updated element in list

    delete:
      operationId: api.cords.delete
      tags:
        - 1-element of points
      summary: Delete a element from the list
      description: Delete a element from the list
      parameters:
        - name: id_element
          in: path
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted a element from list